import type { Metadata } from "next";
import "../globals.css";
import SideBar from "@/components/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex bg-gray-100 h-[calc(100vh-4rem)]">
      <SideBar />
      <div className="w-full flex flex-col h-full py-0 pr-0 md:py-6 md:pr-6">
        <div className="flex flex-col h-full rounded-md  bg-white shadow">
          <div className="h-full">
            <div className="h-full">{children}</div>
          </div>
        </div>
      </div>
    </div>
  );
}
